### ISSUE TITLE
EasyChair upload doesn't work

### ISSUE THREAD

**Issue by clange** [ceurws/ceur-make-ui#16]
We are getting the following error messages:

https://github.com/ceurws/ceur-make-ui/blob/master/CeurMakeGUI/index/ManagingExtract.php#L57

opendir(easyChair/There was a problem with the upload. Please try again./): fail
ed to open dir: No such file or directory

… because `fileName` is not initialised with the right value.

**Comment by ghost** [comment]
@vishnunmenon have tested out with limited easyChair file resources and it works out on his local machine, 
as next steps, we  can look into the following:

1.  we can look into uploading a larger easyChair zip folder as this was possibly a limitation earlier.
2. If (1) goes fine we will have to test it on the server!
