### ISSUE TITLE
Enable updates to countries.json

### ISSUE THREAD

**Issue by clange** [ceurws/ceur-make-ui#6]
Countries change relatively frequently. It would be good to document where countries.json comes from so that the admin can update it. If it's not downloaded from anywhere it would be good to switch from a manually maintained file to some list of countries that can be downloaded from a free source on the Web. If you can't find such a source, I might be able to write a suitable SPARQL query against DBpedia.

At the moment there are some spelling mistakes ("land Islands", "AndorrA"), and some places missing that are recognised as countries by some others, e.g. Kosovo – but it's not worth the effort of fixing them manually.

**Comment by ghost** [comment]
It was taken from a gist at github.

The link to the gist is as followin : https://gist.github.com/keeguon/2310008#gistcomment-869598

SO maybe a more maintained list of countries could be used.

**Comment by vishnunmenon** [comment]
Countries are now taken from RESTful API (https://restcountries.eu/)
